### ISSUE TITLE
Select Target Cell Text on Click

### ISSUE THREAD

**Issue by sobbuh** [denisraslov/react-spreadsheet-grid#24]
Hi, 

I'm looking to select the target cell text using onClick or onFocus (i.e. when user single clicks on a cell, all text is highlighted) 

```
{
                title: () => 'Order',
                value: (row, { active }) => {
                    return (
                        <Input
                        ref="orderInput"
                        value={row.order || 0}
                        onClick={this.handleClick.bind(this)}
                        onChange={this.onFieldChange.bind(this, row.plu[0], 'order')}
                        />
                    )
                }
 
```}

If I do onClick={console.log("clicked")}, I get a console log. 

if I do onClick={this.handleClick.bind(this)} or onClick={this.handleClick} and try to console.log inside the handleClick function, I get no response. 

Any ideas on how I could get this to work? 

Thanks in advance

**Comment by denisraslov** [comment]
Built-in `Input` doesn't have the `onClick` property for now, so `onClick={this.handleClick.bind(this)}` won't work.

You can do the following to solve your problem:
1. Pass `true` for the `focusOnSingleClick` property of `Grid` to set focus on a cell's input upon single clicking it.
2. Copy the code of the built-in Input component from `src/input/index.jsx`, make your own Input using it, change the code of the `prepareFocus` method (select the value of the input there if the `focus` argument is `true`).
3. Use this new input as a content of a cell instead of the built-in Input.

**Comment by sobbuh** [comment]
Hey Denis, 

Perfect, got it working. 

Thanks for your help.
